### ISSUE TITLE
Widoczność ukrytych stron

### ISSUE THREAD

**Issue by Ikswezslo** [Ikswezslo/cms-prototype#118]
Czy ukryte strony powinny być zawsze niewidoczne czy niewidoczne dla osób bez uprawnień w następujących sytuacjach:

- nadstrona/podstrony w widoku strony
- lista z ostatnio dodanymi stronami

**Comment by Vi-Moczulak** [comment]
Zależnie od uprawnień 
- użytkownik widzi wszystkie widoczne strony i swoje ukryte 
- admin widzi wszystkie strony 
- admin uniwersytetu widzi wszystkie widoczne strony i ukryte swojego uniwersytetu
