### ISSUE TITLE
Refaktoryzacja 0.3 

### ISSUE THREAD

**Issue by Vi-Moczulak** [Ikswezslo/cms-prototype#124]

**Comment by Vi-Moczulak** [comment]
- lista page poprawa formatu daty stworzenia hh:mm dd.mm.yyy

**Comment by Mielczarek-wiz** [comment]
- usunąć button "change main page" w akcjach uniwersytetu

**Comment by Vi-Moczulak** [comment]
- usunąć "Strony" z menu użytkownika

**Comment by Ikswezslo** [comment]
- usunąć niepotrzebne pliki .scss i .spec.ts

**Comment by Mielczarek-wiz** [comment]
- naprawić błąd "TypeError: Cannot read properties of undefined (reading 'hidden')"

**Comment by Mielczarek-wiz** [comment]
- zrefaktoryzować wszystkie miejsca, w których powinien wyświetlić się error (success)

**Comment by Mielczarek-wiz** [comment]
Usunięcie wersji 2.7.4 w pliku pom.xml

**Comment by Vi-Moczulak** [comment]
Usunąć Wykorzystane zdjęcia

**Comment by Ikswezslo** [comment]
pom.xml - ustawić wersję na 0.3

**Comment by Ikswezslo** [comment]
Naprawić #169
