### ISSUE TITLE
DOCKERFILE

### ISSUE THREAD

**Issue by Vi-Moczulak** [Ikswezslo/cms-prototype#140]
- [x] Java Spring 
- [x] Angular 
- [ ] PostgreSQL

**Comment by Vi-Moczulak** [comment]
Java Spring 
`docker build -f Dockerfile -t cms . `
`docker run -p 8080:8080 cms`

**Comment by Vi-Moczulak** [comment]
Angular 
`ng build --configuration="production" `
`docker build -t cms-angular` 
`docker run -p 4200:4200 cms-angular`

**Comment by Ikswezslo** [comment]
Resolved by #182
